.\" @(#)analyzeheader.1;
.TH ANALYZEHEADER 1 "6 March 1996" "CNU Tools" "CNU Tools"
.SH NAME
analyzeheader \- ANALYZE print header
.SH SYNOPSIS
.B analyzeheader
.I infile
.SH DESCRIPTION
.LP
.B analyzeheader
prints header information from an ANALYZE file
.SH OPTIONS
.TP
.I infile
input ANALYZE file name with or without .img extension
.SH "SEE ALSO"
.BR analyze2ecat (1),
.BR ecat2analyze (1),
.BR ecatheader (1),
.BR cnuintro (3)
