.\" @(#)DICOMheader.1;
.TH DICOMHEADER 1 "16 January 2003" "CNU Tools" "CNU Tools"
.SH NAME
dicomheader \- DICOM file print header
.SH SYNOPSIS
.B dicomheader
.I infile
\fR[\fB\-help\fR]
\fR[\fB\-terse \fR| \fB\-concise \fR| \fB\-brief \fR| \fB\-normal \fR| \fB\-lengthy \fR| \fB\-verbose \fR| \fB\-tedious\fR]
.SH DESCRIPTION
.LP
.B dicomheader
prints header information from an DICOM file
.SH OPTIONS
.TP
.I infile
input DICOM file name
.TP
.B \-help
print command line options
.TP
\fB\-terse \fR| \fB\-concise \fR| \fB\-brief \fR| \fB\-normal \fR| \fB\-lengthy \fR| \fB\-verbose \fR| \fB\-tedious
options to print more or less info from dicom header
.SH "SEE ALSO"
.BR analyzeheader (1),
.BR ecatheader (1),
.BR sdtheader (1),
.BR cnuintro (3)
