.\" @(#)ecat7header.1;
.TH ECAT7HEADER 1 "27 November 2001" "CNU Tools" "CNU Tools"
.SH NAME
ecat7header \- ECAT7 print header
.SH SYNOPSIS
.B ecat7header
.I infile
.SH DESCRIPTION
.LP
.B ecat7header
prints header information from an ECAT7 file
.SH OPTIONS
.TP
.I infile
input ECAT7 file name
.SH "SEE ALSO"
.BR ecatheader (1),
.BR analyzeheader (1),
.BR cnuintro (3)
