.\" @(#)niftiheader.1;
.TH NIFTIHEADER 1 "10 January 2017" "CNU Tools" "CNU Tools"
.SH NAME
niftiheader \- NIFTI print header
.SH SYNOPSIS
.B niftiheader
.I infile
.SH DESCRIPTION
.LP
.B niftiheader
prints header information from an NIFTI file
.SH OPTIONS
.TP
.I infile
input NIFTI file name with or without .nii extension
.SH "SEE ALSO"
.BR cnuintro (3)
