.\" @(#)analyzeheader.1;
.TH PSYIMGHEADER 1 "6 March 1996" "CNU Tools" "CNU Tools"
.SH NAME
psyimgheader \- print image psyimg header info
.SH SYNOPSIS
.B psyimgheader
.I infile
.SH DESCRIPTION
.LP
.B psyimgheader
prints psyimg header information from any recognized image file
.SH OPTIONS
.TP
.I infile
input image file name
.SH "SEE ALSO"
.BR analyzeheader (1),
.BR ecatheader (1),
.BR ecat7header (1),
.BR niftiheader (1),
.BR dicomheader (1),
.BR sdtheader (1),
.BR cnuintro (3)
