.\" @(#)SDTheader.1;
.TH SDTHEADER 1 "17 January 2003" "CNU Tools" "CNU Tools"
.SH NAME
sdtheader \- SDT file print header
.SH SYNOPSIS
.B sdtheader
.I infile
.SH DESCRIPTION
.LP
.B sdtheader
prints header information from an SDT file
.SH OPTIONS
.TP
.I infile
input SDT file name
.SH "SEE ALSO"
.BR analyzeheader (1),
.BR ecatheader (1),
.BR sdtheader (1),
.BR dicomheader (1),
.BR cnuintro (3)
