.\" @(#)umri2analyze.1;
.TH UMRI2ANALYZE 1 "26 October 1993" "CNU Tools" "CNU Tools"
.SH NAME
umri2analyze \- University of Minnesota MRI to ANALYZE file conversion
.SH SYNOPSIS
.B umri2analyze
.I infile
.I outfile
.SH DESCRIPTION
.LP
.B umri2analyze
converts from University of Minnesota MRI file format to ANALYZE file format
.SH OPTIONS
.TP
.I infile
input MRI file name
.TP
.I outfile
output ANALYZE file name with or without .img extension
.SH "SEE ALSO"
.BR typeconvert (1),
.BR cnuintro (3)
